### ISSUE TITLE
Table background color

### ISSUE THREAD

**Issue by KKhushhalR2405** [KKhushhalR2405/TodoList#2]
Add CSS to change table background color

**Comment by Parth-Gupta10** [comment]
Hey ! I would like to grab this one. Please specify any specific colors you need?

**Comment by KKhushhalR2405** [comment]
Any color of your choice..... I just opened it for the newbies  :P

**Comment by Parth-Gupta10** [comment]
Ok, will be sending PR ASAP.

**Comment by ShipraGaur** [comment]
I want to work too

**Comment by KKhushhalR2405** [comment]
> I want to work too

Yes, you can work. Improve the UI using basic CSS and create a Pull Request. Happy Hacktober  :P
